// <auto-generated />
using System;
using DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DB.Migrations
{
    [DbContext(typeof(FirenzeContext))]
    [Migration("20250129191819_InitDB")]
    partial class InitDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DB.Tipo_Trabajo", b =>
                {
                    b.Property<int>("Id_Tipo_Trabajo_Ttr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Tipo_Trabajo_Ttr"));

                    b.Property<string>("Descripcion_Ttr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Tipo_Trabajo_Ttr");

                    b.ToTable("TipoTrabajos");
                });

            modelBuilder.Entity("DB.Trabajo", b =>
                {
                    b.Property<int>("Id_Trabajo_Tr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Trabajo_Tr"));

                    b.Property<bool>("Adicional_Tr")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion_Tr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Duracion_Tr")
                        .HasColumnType("time");

                    b.Property<int>("Id_Tipo_Trabajo_Tr")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio_Tr")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id_Trabajo_Tr");

                    b.HasIndex("Id_Tipo_Trabajo_Tr");

                    b.ToTable("Trabajos");
                });

            modelBuilder.Entity("DB.Trabajo", b =>
                {
                    b.HasOne("DB.Tipo_Trabajo", "Tipo_Trabajo")
                        .WithMany("Trabajos")
                        .HasForeignKey("Id_Tipo_Trabajo_Tr")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tipo_Trabajo");
                });

            modelBuilder.Entity("DB.Tipo_Trabajo", b =>
                {
                    b.Navigation("Trabajos");
                });
#pragma warning restore 612, 618
        }
    }
}
